version: '3.1'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-9.6.10}-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: secret
    ports:
      - 5432
      - '9003:5432'

  php:
    build: ./docker/php/
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    links:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

networks:
  default:
